USE ddinfoways_staff;

ALTER TABLE tasks
  ADD COLUMN IF NOT EXISTS tags VARCHAR(255),
  ADD COLUMN IF NOT EXISTS attachments TEXT,
  ADD COLUMN IF NOT EXISTS progress INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS estimated_hrs DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS actual_hrs DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS completed_at DATETIME,
  ADD COLUMN IF NOT EXISTS position INT DEFAULT 0;

ALTER TABLE projects
  ADD COLUMN IF NOT EXISTS progress INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS client_name VARCHAR(100),
  ADD COLUMN IF NOT EXISTS budget DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT 0;
